Added a more verbose quick start doc
lawrencegripper/ion pull request #176
Opened 2018-10-01 13:11 UTC by lawrencegripper

Currently work in progress but looking to explain in more detail the system.

2018-10-01 13:32 UTC, jjcollinge commented on docs/Quick Start.md
> +The `frontapi.new_link` event in outputted by the [FrontAPI used to submit items to the pipeline](./../cmd/frontapi). The `file_downloaded` event is what we'll output
in => is

2018-10-01 13:33 UTC, jjcollinge commented on docs/Quick Start.md
> +after we've downloaded the file. Lastly the `-p` specifies the provider to run the module under. In this case we'll use a shared Kuberentes environment and it will run as a [Job](https://kubernetes.i
"Lastly the `-p` flag specifies..."

2018-10-01 13:36 UTC, jjcollinge commented on docs/Quick Start.md
> +So next lets trigger our pipeline with a new URL to download and transcode. We'll use CURL to POST [out request](./data/examplesubmission.json) for the [Big Buck Bunny film](https://peach.blender.org
out => our

2018-10-01 13:37 UTC, jjcollinge commented on docs/Quick Start.md
> +    - `eventMeta`: This is data transferred between events used by the system. Then include links to blob data uploaded by a module so you can debug the flow between modules.
Then include => This includes

2018-10-01 13:38 UTC, jjcollinge commented on docs/Quick Start.md
> +    - `insight`: This is data stored by the module for querying by the user, this could include execution time, items spotted in the video or any arbitrary data for query. You can inspect the putput
putput => output

2018-10-01 13:40 UTC, jjcollinge requested changes
A few typos. Should we link to this from the main README.md too? All good otherwise

2018-10-01 14:52 UTC, lawrencegripper commented
Thanks, yeah good idea I've added in a link in the root readme and hopefully fixed up those typos.

2018-10-05 15:56 UTC, jjcollinge approved these changes

2018-10-05 15:57 UTC, merged